### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by ujifgc** [padrino/padrino-docs#98]
_From @dariocravero on March 18, 2013 19:49_

# List of features to document

## Components
- [ ] Explain `.components`.
- [ ] How to change ORM,
- [ ] How to change renderer,
- [ ] How to change styles processor,
- [ ] How to change scripts,
- [ ] How to change database adapter?

## ...
- [ ] Document invoke_hooks (#1098)
- [ ] Cleanup documentation for fields_for (#939)
- [ ] Gemified apps (added to generation docs)
  - [ ] Detailed explanation on how to handle gemified apps
- [ ] Performance tools guide
- [ ] Project modules (re 0.11 release)
- [ ] Document [padrino-flash](https://github.com/padrino/padrino-framework/blob/master/padrino-core/lib/padrino-core/application/flash.rb) better. Particularly what the story is with `now` and `next`. Also, add some comments to the code from the original repo (https://github.com/Cirex/padrino-flash).
- [ ] Explain [`Padrino.dependency_paths`](https://github.com/padrino/padrino-framework/blob/master/padrino-core/lib/padrino-core/loader.rb#L184-L196).
- [ ] Document [how to write rake tasks](https://github.com/padrino/padrino-framework/issues/1189#issuecomment-15502790).
- [ ] Document CSRF, how it relates to post requests, how to disable it (app-wide or controller-level)
- [ ] Document (See #1475) how to access current request controller and action names
- [ ] Document app gemming and starting and the need of special placement for log, tmp, configs

## Testing
- [ ] How to set the current account  (or the session in general) while testing controllers#1198.

Let's build this list up! :)

_Copied from original issue: padrino/padrino-framework#1137_

**Comment by ujifgc** [comment]
_From @nesquena on March 18, 2013 19:57_

Awesome, thanks definitely want to help get those fleshed out soon.

**Comment by ujifgc** [comment]
_From @dariocravero on March 18, 2013 19:58_

And we will! :dancers:

**Comment by ujifgc** [comment]
_From @Ortuna on March 18, 2013 20:4_

Does this go in padrino-docs ?

**Comment by ujifgc** [comment]
_From @dariocravero on March 18, 2013 20:12_

It does for now @Ortuna. Until we decide whether we move it to the main repo or not.

**Comment by ujifgc** [comment]
_From @skade on March 18, 2013 20:55_

We should especially decide on what system to use. I like middleman alot and would like to get the idea of using something like qed for documentation testing further.

**Comment by ujifgc** [comment]
_From @nesquena on April 9, 2013 7:44_

Notes for CSRF section from @skade 

> CSRF attacks are a severe problem and the safety measures should never be turned off by default.

> You need to pass a parameter called "authenticity_token" with the value "session[:csrf]" on every post request. If you work sessionless for parts of your app (e.g. for an API), you should add:

`set :allow_disabled_csrf, true`

> And disable CSRF on a route-by-route basis:

```
get :foo, :csrf_protection => false do

end
```

> Do only turn of CSRF protection completely if your app works completely sessionless. In that case, you should use another way of validating requests.

**Comment by ujifgc** [comment]
_From @nesquena on January 17, 2016 17:30_

@wikimatze This represents a list of some of the most obvious missing or incomplete documentation. Any help in augmenting the guides with these would be much appreciated.

**Comment by wikimatze** [comment]
Thanks for moving this around, it will take a while to document these and think we to put it, but I'm on my way.
